### ISSUE TITLE
[Bug] - Players unable to open DeathChest after being disconnected/kicked 

### ISSUE THREAD

**Issue by MrPranklez** [DevCyntrix/death-chest#30]
A player disconnected from the server due to some connection issues after having died. Once they returned they were no longer able to open the chest.

How to replicate this issue:

1. Use the following config where chest-protection is enabled ([link to pastebin of config](https://pastebin.com/raw/NuCC88vQ))
2. Die and ensure a chest spawns
3. Disconnect and rejoin and you won't be able to open the chest anymore

**Comment by DevCyntrix** [comment]
Which plugin version do you use?

**Comment by MrPranklez** [comment]
I'm using the latest build on spigot 1.5.17.

**Comment by DevCyntrix** [comment]
Sorry, I cannot reproduce it. But would you like to update the plugin to the newest version. Maybe it is fixed now. :)

**Comment by DevCyntrix** [comment]
Please give me a feedback if you tested it

**Comment by MrPranklez** [comment]
This bug is still happening using the latest version

**Comment by DevCyntrix** [comment]
I tried it again but I can open the chest. Does the plugin throw an exception to the console? Can you send a list of the plugins do you use and would you like to create a video?

**Comment by MrPranklez** [comment]
Here is a clip of me testing it including all the plugins that are currently running.
https://youtu.be/xkvitJFL-6g

DeathChest doesn't throw an exception in console when this bug occurs

**Comment by NonSwag** [comment]
Hey @MrPranklez,
I've done some testing as well but can't reproduce the bug, but...
I found something in the code that relates to the problem (https://github.com/DevCyntrix/death-chest/pull/38/commits/6b301075fc5f94882b9e7692cb875189b7c2f36a).
I changed the condition on how the check is performed and hope it will resolve the issue for you.
[death-chest.zip](https://github.com/DevCyntrix/death-chest/files/11239990/death-chest.zip) (contains the plugin)

**Comment by MrPranklez** [comment]
Hi @NonSwag,

Thanks for the help, however it seems that the jar in the zipped folder only contains a file of 64 bytes so I think something might have gone wrong with that.

**Comment by NonSwag** [comment]
Sorry, my fault, I've compressed a link to the file and not the file itself. 
[death-chest-1.5.19-all.zip](https://github.com/DevCyntrix/death-chest/files/11240026/death-chest-1.5.19-all.zip)

**Comment by DevCyntrix** [comment]
Hi @MrPranklez,

Is the bug fixed now?

**Comment by MrPranklez** [comment]
Sadly not, I removed as good as all plugins and I still get the error when relogging on an account that died. I'm running the latest version of purpur as a server software.

`Bukkit Plugins:
BungeeGuard, CoreProtect, DeathChest, floodgate, LiteBans, LuckPerms, PlaceholderAPI, ProtocolLib, VoidGen, WorldGuard`

**Comment by NonSwag** [comment]
Could you try it again using an original paper release?

All performance enhancements from purpur are already merged into paper.
In theory, you don't need purpur anymore. (except you want to ride any mob)

**Comment by MrPranklez** [comment]
@DevCyntrix had messaged me on Discord on the matter and I did some further testing and using the last build he sent me the issue was resolved. I have tested it with the latest build of paper and purpur.
